const products = [
  {
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "$ 250",
    discount: "$ 35",
    image: "/src/assets/images/products__images/Syltherine.png",
    type: "small",
    place: "dining",
  },
  {
    name: "Leviosa",
    description: "Stylish cafe chair",
    price: "$ 100",
    discount: "",
    image: "/src/assets/images/products__images/Leviosa.png",
    type: "small",
    place: "living",
  },
  {
    name: "Lolito",
    description: "Luxury big sofa",
    price: "$ 700",
    discount: "$ 140",
    image: "/src/assets/images/products__images/Lolito.png",
    type: "large",
    place: "bedroom",
  },
  {
    name: "Respira",
    description: "Outdoor bar table and stool",
    price: "$ 500",
    discount: "",
    image: "/src/assets/images/products__images/Respira.png",
    type: "large",
    place: "living",
  },
  {
    name: "Grifo",
    description: "Night lamp",
    price: "$ 50",
    discount: "",
    image: "/src/assets/images/products__images/Grifo.png",
    type: "other",
    place: "bedroom",
  },
  {
    name: "Muggo",
    description: "Small mug",
    price: "$ 350",
    discount: "",
    image: "/src/assets/images/products__images/Muggo.png",
    type: "large",
    place: "dining",
  },
  {
    name: "Pingky",
    description: "Cute bed set",
    price: "$ 700",
    discount: "$ 140",
    image: "/src/assets/images/products__images/Pingky.png",
    type: "large",
    place: "dining",
  },
  {
    name: "Potty",
    description: "Minimalist flower pot",
    price: "$ 500",
    discount: "",
    image: "/src/assets/images/products__images/Lolito.png",
    type: "large",
  },
  {
    name: "Potty",
    description: "Minimalist flower pot",
    price: "$ 500",
    discount: "",
    image: "/src/assets/images/products__images/Lolito.png",
  },
];

const localProducts = localStorage.setItem(
  "localProducts",
  JSON.stringify(products)
);
