import { stateFeatures } from "./state.js";

const productsArr = [
  {
    id: 0,
    name: "Syltherine",
    description: "Stylish cafe chair",
    currency: "$",
    price: 250,
    discount: 35,
    image: "/src/assets/images/products__images/Syltherine.png",
    type: "small",
    place: "dining",
  },
  {
    id: 1,
    name: "Leviosa",
    description: "Stylish cafe chair",
    currency: "$",
    price: 100,
    discount: "",
    image: "/src/assets/images/products__images/Leviosa.png",
    type: "small",
    place: "living",
  },
  {
    id: 2,
    name: "Lolito",
    description: "Luxury big sofa",
    currency: "$",
    price: 700,
    discount: 140,
    image: "/src/assets/images/products__images/Lolito.png",
    type: "large",
    place: "bedroom",
  },
  {
    id: 3,
    name: "Respira",
    description: "Outdoor bar table and stool",
    currency: "$",
    price: 500,
    discount: "",
    image: "/src/assets/images/products__images/Respira.png",
    type: "large",
    place: "living",
  },
  {
    id: 4,
    name: "Grifo",
    description: "Night lamp",
    currency: "$",
    price: 50,
    discount: "",
    image: "/src/assets/images/products__images/Grifo.png",
    type: "other",
    place: "bedroom",
  },
  {
    id: 5,
    name: "Muggo",
    description: "Small mug",
    currency: "$",
    price: 350,
    discount: "",
    image: "/src/assets/images/products__images/Muggo.png",
    type: "large",
    place: "dining",
  },
  {
    id: 6,
    name: "Pingky",
    description: "Cute bed set",
    currency: "$",
    price: 700,
    discount: 140,
    image: "/src/assets/images/products__images/Pingky.png",
    type: "large",
    place: "dining",
  },
  {
    id: 7,
    name: "Potty",
    description: "Minimalist flower pot",
    currency: "$",
    price: 500,
    discount: "",
    image: "/src/assets/images/products__images/Lolito.png",
    type: "large",
  },
  {
    id: 8,
    name: "Potty",
    description: "Minimalist flower pot",
    currency: "$",
    price: 500,
    discount: "",
    image: "/src/assets/images/products__images/Lolito.png",
  },
];

localStorage.setItem(stateFeatures.products, JSON.stringify(productsArr));
